#!/bin/sh

USAGE='Clone a git repo with support for the gitflow branching model.
    usage: git flow clone [options] [--] <repo> [<dir>]
  options: -p Create intermediate directories as required.'

# Something went wrong
function fail { echo "$USAGE" >&2; exit 1; }

# Extracts a DIR and REPO when given a URL
function parse_url {
  web='https?://[^/]+/'
  ssh='[^:]+:'
  path=`echo "$1" | sed -E "s,($web|$ssh),,"`
  DIR=`dirname "$path"`
  REPO=`basename "$path" | sed -E "s/.git$//"`
}

# Clones a repo and performs Gitflow setup
function clone_repo {
  git clone $1 -b master || fail
  cd "$REPO"
  if (git checkout develop 2> /dev/null); then
    git flow init -d
  else
    echo "converting a non-Gitflow repo into a Gitflow repo"
    git flow init -d
    git push -u origin develop
  fi
}

# Missing <repo> arg
if [ $# -eq 0 ]; then fail; fi

if [ $1 = '-p' ]; then
  # Copy directory structre
  parse_url $2
  mkdir -p "$DIR" || fail
  cd "$DIR"
  clone_repo $2
  echo "Gitflow repo cloned to ${DIR}/${REPO}"
else
  # Clone in place
  parse_url $1
  clone_repo $1
  echo "Gitflow repo cloned to ${REPO}"
fi

# exit so we don't continue continue up the git call stack
exit 0
